excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://s00157412.github.io
title: s00157412
tagline: Things everyone should know
description: This is my project work while attending Sligo I.T
paginate: 5